server:
  port: 8088
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSl=false
    username: root
    password: ivanna83
    driver-class-name: com.mysql.jdbc.Driver